server:
  port: 8082

spring:
  application:
    name: backend-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sentinelmesh
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aetherflow-backend-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    com.aetherflow: DEBUG
    org.hibernate.SQL: INFO
