# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xba\x01\n\x0e\x41nomalyRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x11\n\triskScore\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x16\n\x0e\x65ventTimestamp\x18\x04 \x01(\x03\x12\x0b\n\x03\x63pu\x18\x05 \x01(\x01\x12\x0e\n\x06memory\x18\x06 \x01(\x01\x12\x14\n\x0cresponseTime\x18\x07 \x01(\x01\x12\x14\n\x0c\x66\x61iledLogins\x18\x08 \x01(\x05\x12\x16\n\x0enetworkPackets\x18\t \x01(\x03\"O\n\x0f\x41nomalyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nincidentId\x18\x02 \x01(\t\x12\x18\n\x10mitigationAction\x18\x03 \x01(\t2X\n\x0e\x41nomalyService\x12\x46\n\rReportAnomaly\x12\x19.telemetry.AnomalyRequest\x1a\x1a.telemetry.AnomalyResponseB\x1f\n\x1b\x63om.aetherflow.backend.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.aetherflow.backend.grpcP\001'
  _globals['_ANOMALYREQUEST']._serialized_start=31
  _globals['_ANOMALYREQUEST']._serialized_end=217
  _globals['_ANOMALYRESPONSE']._serialized_start=219
  _globals['_ANOMALYRESPONSE']._serialized_end=298
  _globals['_ANOMALYSERVICE']._serialized_start=300
  _globals['_ANOMALYSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
