# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import telemetry_pb2 as telemetry__pb2


class AnomalyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportAnomaly = channel.unary_unary(
                '/telemetry.AnomalyService/ReportAnomaly',
                request_serializer=telemetry__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=telemetry__pb2.AnomalyResponse.FromString,
                )


class AnomalyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportAnomaly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportAnomaly': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAnomaly,
                    request_deserializer=telemetry__pb2.AnomalyRequest.FromString,
                    response_serializer=telemetry__pb2.AnomalyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.AnomalyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnomalyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportAnomaly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/telemetry.AnomalyService/ReportAnomaly',
            telemetry__pb2.AnomalyRequest.SerializeToString,
            telemetry__pb2.AnomalyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
