server:
  port: 8081

spring:
  application:
    name: ingestion-service
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

logging:
  level:
    root: INFO
    com.aetherflow: DEBUG
    org.springframework.kafka: INFO
